/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_search_hints`]
#[derive(Clone, Debug)]
pub struct GetSearchHintsParams {
    /// The search term to filter on.
    pub search_term: String,
    /// Optional. The record index to start at. All items with a lower index will be dropped from the results.
    pub start_index: Option<i32>,
    /// Optional. The maximum number of records to return.
    pub limit: Option<i32>,
    /// Optional. Supply a user id to search within a user's library or omit to search all.
    pub user_id: Option<String>,
    /// If specified, only results with the specified item types are returned. This allows multiple, comma delimited.
    pub include_item_types: Option<Vec<models::BaseItemKind>>,
    /// If specified, results with these item types are filtered out. This allows multiple, comma delimited.
    pub exclude_item_types: Option<Vec<models::BaseItemKind>>,
    /// If specified, only results with the specified media types are returned. This allows multiple, comma delimited.
    pub media_types: Option<Vec<models::MediaType>>,
    /// If specified, only children of the parent are returned.
    pub parent_id: Option<String>,
    /// Optional filter for movies.
    pub is_movie: Option<bool>,
    /// Optional filter for series.
    pub is_series: Option<bool>,
    /// Optional filter for news.
    pub is_news: Option<bool>,
    /// Optional filter for kids.
    pub is_kids: Option<bool>,
    /// Optional filter for sports.
    pub is_sports: Option<bool>,
    /// Optional filter whether to include people.
    pub include_people: Option<bool>,
    /// Optional filter whether to include media.
    pub include_media: Option<bool>,
    /// Optional filter whether to include genres.
    pub include_genres: Option<bool>,
    /// Optional filter whether to include studios.
    pub include_studios: Option<bool>,
    /// Optional filter whether to include artists.
    pub include_artists: Option<bool>
}


/// struct for typed successes of method [`get_search_hints`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSearchHintsSuccess {
    Status200(models::SearchHintResult),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_search_hints`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSearchHintsError {
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn get_search_hints(configuration: &configuration::Configuration, params: GetSearchHintsParams) -> Result<ResponseContent<GetSearchHintsSuccess>, Error<GetSearchHintsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let search_term = params.search_term;
    let start_index = params.start_index;
    let limit = params.limit;
    let user_id = params.user_id;
    let include_item_types = params.include_item_types;
    let exclude_item_types = params.exclude_item_types;
    let media_types = params.media_types;
    let parent_id = params.parent_id;
    let is_movie = params.is_movie;
    let is_series = params.is_series;
    let is_news = params.is_news;
    let is_kids = params.is_kids;
    let is_sports = params.is_sports;
    let include_people = params.include_people;
    let include_media = params.include_media;
    let include_genres = params.include_genres;
    let include_studios = params.include_studios;
    let include_artists = params.include_artists;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/Search/Hints", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = start_index {
        local_var_req_builder = local_var_req_builder.query(&[("startIndex", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = limit {
        local_var_req_builder = local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = user_id {
        local_var_req_builder = local_var_req_builder.query(&[("userId", &local_var_str.to_string())]);
    }
    local_var_req_builder = local_var_req_builder.query(&[("searchTerm", &search_term.to_string())]);
    if let Some(ref local_var_str) = include_item_types {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("includeItemTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("includeItemTypes", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = exclude_item_types {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("excludeItemTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("excludeItemTypes", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = media_types {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("mediaTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("mediaTypes", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = parent_id {
        local_var_req_builder = local_var_req_builder.query(&[("parentId", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = is_movie {
        local_var_req_builder = local_var_req_builder.query(&[("isMovie", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = is_series {
        local_var_req_builder = local_var_req_builder.query(&[("isSeries", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = is_news {
        local_var_req_builder = local_var_req_builder.query(&[("isNews", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = is_kids {
        local_var_req_builder = local_var_req_builder.query(&[("isKids", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = is_sports {
        local_var_req_builder = local_var_req_builder.query(&[("isSports", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = include_people {
        local_var_req_builder = local_var_req_builder.query(&[("includePeople", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = include_media {
        local_var_req_builder = local_var_req_builder.query(&[("includeMedia", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = include_genres {
        local_var_req_builder = local_var_req_builder.query(&[("includeGenres", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = include_studios {
        local_var_req_builder = local_var_req_builder.query(&[("includeStudios", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = include_artists {
        local_var_req_builder = local_var_req_builder.query(&[("includeArtists", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_apikey) = local_var_configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        let local_var_entity: Option<GetSearchHintsSuccess> = serde_json::from_str(&local_var_content).ok();
        let local_var_result = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Ok(local_var_result)
    } else {
        let local_var_entity: Option<GetSearchHintsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

