/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityLogEntryStartMessage : Activity log entry start message.  Data is the timing data encoded as \"$initialDelay,$interval\" in ms.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogEntryStartMessage {
    /// Gets or sets the data.
    #[serde(rename = "Data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    /// The different kinds of messages that are used in the WebSocket api.
    #[serde(rename = "MessageType", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<models::SessionMessageType>,
}

impl ActivityLogEntryStartMessage {
    /// Activity log entry start message.  Data is the timing data encoded as \"$initialDelay,$interval\" in ms.
    pub fn new() -> ActivityLogEntryStartMessage {
        ActivityLogEntryStartMessage {
            data: None,
            message_type: None,
        }
    }
}

