/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LibraryChangedMessage : Library changed message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryChangedMessage {
    /// Gets or sets the data.
    #[serde(rename = "Data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<Box<models::LibraryUpdateInfo>>>,
    /// Gets or sets the message id.
    #[serde(rename = "MessageId", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<uuid::Uuid>,
    /// The different kinds of messages that are used in the WebSocket api.
    #[serde(rename = "MessageType", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<models::SessionMessageType>,
}

impl LibraryChangedMessage {
    /// Library changed message.
    pub fn new() -> LibraryChangedMessage {
        LibraryChangedMessage {
            data: None,
            message_id: None,
            message_type: None,
        }
    }
}

