/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetadataRefreshMode {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "ValidationOnly")]
    ValidationOnly,
    #[serde(rename = "Default")]
    Default,
    #[serde(rename = "FullRefresh")]
    FullRefresh,

}

impl std::fmt::Display for MetadataRefreshMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::ValidationOnly => write!(f, "ValidationOnly"),
            Self::Default => write!(f, "Default"),
            Self::FullRefresh => write!(f, "FullRefresh"),
        }
    }
}

impl Default for MetadataRefreshMode {
    fn default() -> MetadataRefreshMode {
        Self::None
    }
}

