/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetadataField : Enum MetadataFields.
/// Enum MetadataFields.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetadataField {
    #[serde(rename = "Cast")]
    Cast,
    #[serde(rename = "Genres")]
    Genres,
    #[serde(rename = "ProductionLocations")]
    ProductionLocations,
    #[serde(rename = "Studios")]
    Studios,
    #[serde(rename = "Tags")]
    Tags,
    #[serde(rename = "Name")]
    Name,
    #[serde(rename = "Overview")]
    Overview,
    #[serde(rename = "Runtime")]
    Runtime,
    #[serde(rename = "OfficialRating")]
    OfficialRating,

}

impl std::fmt::Display for MetadataField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cast => write!(f, "Cast"),
            Self::Genres => write!(f, "Genres"),
            Self::ProductionLocations => write!(f, "ProductionLocations"),
            Self::Studios => write!(f, "Studios"),
            Self::Tags => write!(f, "Tags"),
            Self::Name => write!(f, "Name"),
            Self::Overview => write!(f, "Overview"),
            Self::Runtime => write!(f, "Runtime"),
            Self::OfficialRating => write!(f, "OfficialRating"),
        }
    }
}

impl Default for MetadataField {
    fn default() -> MetadataField {
        Self::Cast
    }
}

