/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlaylistDto : DTO for playlists.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistDto {
    /// Gets or sets a value indicating whether the playlist is publicly readable.
    #[serde(rename = "OpenAccess", skip_serializing_if = "Option::is_none")]
    pub open_access: Option<bool>,
    /// Gets or sets the share permissions.
    #[serde(rename = "Shares", skip_serializing_if = "Option::is_none")]
    pub shares: Option<Vec<models::PlaylistUserPermissions>>,
    /// Gets or sets the item ids.
    #[serde(rename = "ItemIds", skip_serializing_if = "Option::is_none")]
    pub item_ids: Option<Vec<uuid::Uuid>>,
}

impl PlaylistDto {
    /// DTO for playlists.
    pub fn new() -> PlaylistDto {
        PlaylistDto {
            open_access: None,
            shares: None,
            item_ids: None,
        }
    }
}

