/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreviousItemRequestDto : Class PreviousItemRequestDto.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviousItemRequestDto {
    /// Gets or sets the playing item identifier.
    #[serde(rename = "PlaylistItemId", skip_serializing_if = "Option::is_none")]
    pub playlist_item_id: Option<uuid::Uuid>,
}

impl PreviousItemRequestDto {
    /// Class PreviousItemRequestDto.
    pub fn new() -> PreviousItemRequestDto {
        PreviousItemRequestDto {
            playlist_item_id: None,
        }
    }
}

