/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicSystemInfo {
    /// Gets or sets the local address.
    #[serde(rename = "LocalAddress", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_address: Option<Option<String>>,
    /// Gets or sets the name of the server.
    #[serde(rename = "ServerName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server_name: Option<Option<String>>,
    /// Gets or sets the server version.
    #[serde(rename = "Version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<String>>,
    /// Gets or sets the product name. This is the AssemblyProduct name.
    #[serde(rename = "ProductName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_name: Option<Option<String>>,
    /// Gets or sets the operating system.
    #[serde(rename = "OperatingSystem", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub operating_system: Option<Option<String>>,
    /// Gets or sets the id.
    #[serde(rename = "Id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    /// Gets or sets a value indicating whether the startup wizard is completed.
    #[serde(rename = "StartupWizardCompleted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub startup_wizard_completed: Option<Option<bool>>,
}

impl PublicSystemInfo {
    pub fn new() -> PublicSystemInfo {
        PublicSystemInfo {
            local_address: None,
            server_name: None,
            version: None,
            product_name: None,
            operating_system: None,
            id: None,
            startup_wizard_completed: None,
        }
    }
}

