/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RestartRequiredMessage : Restart required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestartRequiredMessage {
    /// Gets or sets the message id.
    #[serde(rename = "MessageId", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<uuid::Uuid>,
    /// The different kinds of messages that are used in the WebSocket api.
    #[serde(rename = "MessageType", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<models::SessionMessageType>,
}

impl RestartRequiredMessage {
    /// Restart required.
    pub fn new() -> RestartRequiredMessage {
        RestartRequiredMessage {
            message_id: None,
            message_type: None,
        }
    }
}

