/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionsStopMessage : Sessions stop message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionsStopMessage {
    /// The different kinds of messages that are used in the WebSocket api.
    #[serde(rename = "MessageType", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<models::SessionMessageType>,
}

impl SessionsStopMessage {
    /// Sessions stop message.
    pub fn new() -> SessionsStopMessage {
        SessionsStopMessage {
            message_type: None,
        }
    }
}

