/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.10.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebSocketMessage : Represents the possible websocket types
/// Represents the possible websocket types
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebSocketMessage {
    InboundWebSocketMessage(Box<models::InboundWebSocketMessage>),
    OutboundWebSocketMessage(Box<models::OutboundWebSocketMessage>),
}

impl Default for WebSocketMessage {
    fn default() -> Self {
        Self::InboundWebSocketMessage(Default::default())
    }
}

