use jellyfin_api::apis::{
    artists_api::GetArtistsParams, image_api::GetItemImageParams, items_api::GetItemsParams,
    playlists_api::GetPlaylistItemsParams,
};

pub trait JFDefault {
    fn jf_default() -> Self;
}

impl JFDefault for GetItemImageParams {
    fn jf_default() -> Self {
        Self {
            item_id: String::new(),
            image_type: String::new(),
            max_width: None,
            max_height: None,
            width: None,
            height: None,
            quality: None,
            fill_width: None,
            fill_height: None,
            tag: None,
            format: None,
            percent_played: None,
            unplayed_count: None,
            blur: None,
            background_color: None,
            foreground_layer: None,
            image_index: None,
        }
    }
}

impl JFDefault for GetItemsParams {
    fn jf_default() -> Self {
        Self {
            user_id: None,
            max_official_rating: None,
            has_theme_song: None,
            has_theme_video: None,
            has_subtitles: None,
            has_special_feature: None,
            has_trailer: None,
            adjacent_to: None,
            index_number: None,
            parent_index_number: None,
            has_parental_rating: None,
            is_hd: None,
            is4_k: None,
            location_types: None,
            exclude_location_types: None,
            is_missing: None,
            is_unaired: None,
            min_community_rating: None,
            min_critic_rating: None,
            min_premiere_date: None,
            min_date_last_saved: None,
            min_date_last_saved_for_user: None,
            max_premiere_date: None,
            has_overview: None,
            has_imdb_id: None,
            has_tmdb_id: None,
            has_tvdb_id: None,
            is_movie: None,
            is_series: None,
            is_news: None,
            is_kids: None,
            is_sports: None,
            exclude_item_ids: None,
            start_index: None,
            limit: None,
            recursive: None,
            search_term: None,
            sort_order: None,
            parent_id: None,
            fields: None,
            exclude_item_types: None,
            include_item_types: None,
            filters: None,
            is_favorite: None,
            media_types: None,
            image_types: None,
            sort_by: None,
            is_played: None,
            genres: None,
            official_ratings: None,
            tags: None,
            years: None,
            enable_user_data: None,
            image_type_limit: None,
            enable_image_types: None,
            person: None,
            person_ids: None,
            person_types: None,
            studios: None,
            artists: None,
            exclude_artist_ids: None,
            artist_ids: None,
            album_artist_ids: None,
            contributing_artist_ids: None,
            albums: None,
            album_ids: None,
            ids: None,
            video_types: None,
            min_official_rating: None,
            is_locked: None,
            is_place_holder: None,
            has_official_rating: None,
            collapse_box_set_items: None,
            min_width: None,
            min_height: None,
            max_width: None,
            max_height: None,
            is3_d: None,
            series_status: None,
            name_starts_with_or_greater: None,
            name_starts_with: None,
            name_less_than: None,
            studio_ids: None,
            genre_ids: None,
            enable_total_record_count: None,
            enable_images: None,
        }
    }
}

impl JFDefault for GetArtistsParams {
    fn jf_default() -> Self {
        Self {
            min_community_rating: None,
            start_index: None,
            limit: None,
            search_term: None,
            parent_id: None,
            fields: None,
            exclude_item_types: None,
            include_item_types: None,
            filters: None,
            is_favorite: None,
            media_types: None,
            genres: None,
            genre_ids: None,
            official_ratings: None,
            tags: None,
            years: None,
            enable_user_data: None,
            image_type_limit: None,
            enable_image_types: None,
            person: None,
            person_ids: None,
            person_types: None,
            studios: None,
            studio_ids: None,
            user_id: None,
            name_starts_with_or_greater: None,
            name_starts_with: None,
            name_less_than: None,
            sort_by: None,
            sort_order: None,
            enable_images: None,
            enable_total_record_count: None,
        }
    }
}

impl JFDefault for GetPlaylistItemsParams {
    fn jf_default() -> Self {
        Self {
            playlist_id: String::new(),
            user_id: None,
            start_index: None,
            limit: None,
            fields: None,
            enable_images: None,
            enable_user_data: None,
            image_type_limit: None,
            enable_image_types: None,
        }
    }
}
